apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bitwarden-secrets.lerentis.uploadfilter24
spec:
  scope: Namespaced
  group: lerentis.uploadfilter24
  names:
    kind: BitwardenSecret
    plural: bitwarden-secrets
    singular: bitwarden-secret
    shortNames:
      - bws
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
