FROM ubuntu:22.04

RUN apt-get update && apt-get install -y curl

RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
 && mv kubectl /usr/bin/kubectl \
 && chmod +x /usr/bin/kubectl

ADD example.yaml /example.yaml
ADD example_dockerlogin.yaml /example_dockerlogin.yaml
ADD example_template.yaml /example_template.yaml

ADD utils/test.sh /test.sh

ENTRYPOINT [ "/test.sh" ]