---
apiVersion: "lerentis.uploadfilter24.eu/v1beta6"
kind: BitwardenTemplate
metadata:
  name: test
spec:
  filename: "config.yaml"
  name: "test-template"
  namespace: "default"
  labels:
    key: value
    app: example-app
  template: |
    ---
    api:
      enabled: True
      key: {{ bitwarden_lookup("466fc4b0-ffca-4444-8d88-b59d4de3d928", "fields", "key") }}
      allowCrossOrigin: false
      apps:
        "some.app.identifier:some_version":
          pubkey: {{ bitwarden_lookup("466fc4b0-ffca-4444-8d88-b59d4de3d928", "fields", "public_key") }}
          enabled: true
          username: {{ bitwarden_lookup_with_name("Some/App/Identifier/Path", "SecretName", "login", "username") }}
          specialField: {{ bitwarden_lookup_with_name("Some/App/Identifier/Path", "SecretName", "fields", "specialField") }}
          pvtkey: {{ bitwarden_lookup_with_name("Some/App/Identifier/Path", "SecretName", "attachment", "private_key") }}
