---
apiVersion: "lerentis.uploadfilter24.eu/v1beta8"
kind: BitwardenTemplate
metadata:
  name: test
spec:
  name: "test-template"
  namespace: "default"
  labels:
    key: value
    app: example-app
  annotations:
    custom.annotation: is-used
  content:
    - element:
        filename: config.yaml
        template: |
          ---
          api:
            enabled: True
            key: {{ bitwarden_lookup("466fc4b0-ffca-4444-8d88-b59d4de3d928", "fields", "key") }}
            allowCrossOrigin: false
            apps:
              "some.app.identifier:some_version":
                pubkey: {{ bitwarden_lookup("466fc4b0-ffca-4444-8d88-b59d4de3d928", "fields", "public_key") }}
                enabled: true
    - element:
        filename: config2.yaml
        template: |
          ---
          api:
            enabled: True
            key: {{ bitwarden_lookup("466fc4b0-ffca-4444-8d88-b59d4de3d928", "fields", "key") }}
            allowCrossOrigin: false
            apps:
              "some.app.identifier:some_version":
                pubkey: {{ bitwarden_lookup("466fc4b0-ffca-4444-8d88-b59d4de3d928", "fields", "public_key") }}
                enabled: false
