---
apiVersion: "lerentis.uploadfilter24.eu/v1beta2"
kind: BitwardenSecret
metadata:
  name: test
spec:
  content:
    - element:
        secretName: username
        secretRef: nameofUser 
    - element:
        secretName: password
        secretRef: passwordOfUser 
  id: "88781348-c81c-4367-9801-550360c21295"
  name: "test-secret"
  namespace: "default"