---
apiVersion: "lerentis.uploadfilter24.eu/v1beta4"
kind: BitwardenSecret
metadata:
  name: test
spec:
  content:
    - element:
        secretName: username
        secretRef: nameofUser 
        secretScope: login
    - element:
        secretName: password
        secretRef: passwordOfUser 
        secretScope: login
  id: "88781348-c81c-4367-9801-550360c21295"
  name: "test-secret"
  namespace: "default"
---
apiVersion: "lerentis.uploadfilter24.eu/v1beta4"
kind: BitwardenSecret
metadata:
  name: test-scope
spec:
  content:
    - element:
        secretName: public_key
        secretRef: pubKey 
        secretScope: fields
  id: "466fc4b0-ffca-4444-8d88-b59d4de3d928"
  name: "test-scope"
  namespace: "default"