---
apiVersion: "lerentis.uploadfilter24.eu/v1beta7"
kind: BitwardenSecret
metadata:
  name: test
  namespace: default
spec:
  content:
    - element:
        secretName: username
        secretRef: nameofUser 
        secretScope: login
    - element:
        secretName: password
        secretRef: passwordOfUser 
        secretScope: login
  id: "88781348-c81c-4367-9801-550360c21295"
  name: "test-secret"
  secretType: Opaque
  namespace: "default"
  labels:
    key: value
    app: example-app
  annotations:
    custom.annotation: is-used
---
apiVersion: "lerentis.uploadfilter24.eu/v1beta6"
kind: BitwardenSecret
metadata:
  name: test-scope
spec:
  content:
    - element:
        secretName: public_key
        secretRef: pubKey 
        secretScope: fields
  id: "466fc4b0-ffca-4444-8d88-b59d4de3d928"
  name: "test-scope"
  namespace: "default"