apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: bitwarden-crd-operator
build:
  artifacts:
    - image: ghcr.io/lerentis/bitwarden-crd-operator
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: bitwarden-crd-operator
        chartPath: charts/bitwarden-crd-operator
        valuesFiles:
          - ./charts/bitwarden-crd-operator/myvalues.yaml
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_ghcr_io_lerentis_bitwarden_crd_operator}}"
          image.tag: "{{.IMAGE_TAG_ghcr_io_lerentis_bitwarden_crd_operator}}@{{.IMAGE_DIGEST_ghcr_io_lerentis_bitwarden_crd_operator}}"
test:
  - image: ghcr.io/lerentis/bitwarden-crd-operator
    custom:
      - command: ./utils/test.sh
        timeoutSeconds: 60
