apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: bitwarden-crd-operator
build:
  artifacts:
    - image: ghcr.io/lerentis/bitwarden-crd-operator
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: bitwarden-crd-operator
        chartPath: charts/bitwarden-crd-operator
        valuesFiles:
          - env/values.yaml
        version: v0.13.0
