apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: bitwarden-crd-operator
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: ghcr.io/lerentis/bitwarden-crd-operator
      docker:
        dockerfile: Dockerfile
    - image: integration-test-container
      docker:
        dockerfile: Dockerfile.test
deploy:
  helm:
    releases:
      - name: bitwarden-crd-operator
        chartPath: charts/bitwarden-crd-operator
        valuesFiles:
          - ./charts/bitwarden-crd-operator/myvalues.yaml
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_ghcr_io_lerentis_bitwarden_crd_operator}}"
          image.tag: "{{.IMAGE_TAG_ghcr_io_lerentis_bitwarden_crd_operator}}@{{.IMAGE_DIGEST_ghcr_io_lerentis_bitwarden_crd_operator}}"
verify:
  - name: integration-test-container
    container:
      name: integration-test-container
      image: "integration-test-container:a11852f8bb9bf99553238e1fa29206421c72801df5da96ccf9f77ebd069f815f"
    executionMode:
      kubernetesCluster: {}
