---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bitwarden-secrets.lerentis.uploadfilter24.eu
spec:
  scope: Namespaced
  group: lerentis.uploadfilter24.eu
  names:
    kind: BitwardenSecret
    plural: bitwarden-secrets
    singular: bitwarden-secret
    shortNames:
      - bws
  versions:
    - name: v1beta5
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                content:
                  type: array
                  items:
                    type: object
                    properties:
                      element:
                        type: object
                        properties:
                          secretName:
                            type: string
                          secretRef:
                            type: string
                          secretScope:
                            type: string
                        required:
                          - secretName
                id:
                  type: string
                item_name:
                  type: string
                collection_path:
                  type: string
                namespace:
                  type: string
                name:
                  type: string
              required:
                - namespace
                - name
              oneOf:
              - required:
                  - id
              - required:
                  - item_name
                  - collection_path
