---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bitwarden-secrets.lerentis.uploadfilter24.eu
spec:
  scope: Namespaced
  group: lerentis.uploadfilter24.eu
  names:
    kind: BitwardenSecret
    plural: bitwarden-secrets
    singular: bitwarden-secret
    shortNames:
      - bws
  versions:
    - name: v1beta4
      served: true
      storage: false
      deprecated: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                content:
                  type: array
                  items:
                    type: object
                    properties:
                      element:
                        type: object
                        properties:
                          secretName:
                            type: string
                          secretRef:
                            type: string
                          secretScope:
                            type: string
                        required:
                          - secretName
                id:
                  type: string
                namespace:
                  type: string
                name:
                  type: string
              required:
                - id
                - namespace
                - name
    - name: v1beta5
      served: true
      storage: false
      deprecated: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                content:
                  type: array
                  items:
                    type: object
                    properties:
                      element:
                        type: object
                        properties:
                          secretName:
                            type: string
                          secretRef:
                            type: string
                          secretScope:
                            type: string
                        required:
                          - secretName
                id:
                  type: string
                namespace:
                  type: string
                name:
                  type: string
                labels:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
              required:
                - id
                - namespace
                - name
    - name: v1beta6
      served: true
      storage: false
      deprecated: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                content:
                  type: array
                  items:
                    type: object
                    properties:
                      element:
                        type: object
                        properties:
                          secretName:
                            type: string
                          secretRef:
                            type: string
                          secretScope:
                            type: string
                        required:
                          - secretName
                id:
                  type: string
                namespace:
                  type: string
                name:
                  type: string
                labels:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                annotations:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
              required:
                - id
                - namespace
                - name
    - name: v1beta7
      served: true
      storage: false
      deprecated: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                content:
                  type: array
                  items:
                    type: object
                    properties:
                      element:
                        type: object
                        properties:
                          secretName:
                            type: string
                          secretRef:
                            type: string
                          secretScope:
                            type: string
                        required:
                          - secretName
                id:
                  type: string
                namespace:
                  type: string
                name:
                  type: string
                secretType: 
                  type: string
                labels:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                annotations:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
              required:
                - id
                - namespace
                - name
    - name: v1beta8
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                content:
                  type: array
                  items:
                    type: object
                    properties:
                      element:
                        type: object
                        properties:
                          secretName:
                            type: string
                          secretRef:
                            type: string
                          secretScope:
                            type: string
                        required:
                          - secretName
                id:
                  type: string
                namespace:
                  type: string
                name:
                  type: string
                secretType: 
                  type: string
                labels:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                annotations:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
              required:
                - id
                - namespace
                - name