apiVersion: v2
name: bitwarden-crd-operator
description: Deploy the Bitwarden CRD Operator

type: application

version: "v0.11.3"

appVersion: "0.10.3"

keywords:
  - operator
  - bitwarden
  - vaultwarden

icon: https://lerentis.github.io/bitwarden-crd-operator/logo.png

home: https://lerentis.github.io/bitwarden-crd-operator/

sources:
  - https://github.com/Lerentis/bitwarden-crd-operator

kubeVersion: ">= 1.23.0-0"

maintainers:
  - name: lerentis
    email: lerentis+helm@uploadfilter24.eu

annotations:
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/Lerentis/bitwarden-crd-operator
  artifacthub.io/crds: |
    - kind: BitwardenSecret
      version: v1beta5
      name: bitwarden-secret
      displayName: Bitwarden Secret
      description: Management Object to create secrets from bitwarden
    - kind: RegistryCredential
      version: v1beta5
      name: registry-credential
      displayName: Regestry Credentials
      description: Management Object to create regestry secrets from bitwarden
    - kind: BitwardenTemplate
      version: v1beta5
      name: bitwarden-template
      displayName: Bitwarden Template
      description: Management Object to create secrets from a jinja template with a bitwarden lookup
  artifacthub.io/crdsExamples: |
    - apiVersion: lerentis.uploadfilter24.eu/v1beta5
      kind: BitwardenSecret
      metadata:
        name: test
      spec:
        content:
          - element:
              secretName: username
              secretRef: nameofUser
          - element:
              secretName: password
              secretRef: passwordOfUser
        id: "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"
        name: "test-secret"
        namespace: "default"
        labels:
          key: value
    - apiVersion: lerentis.uploadfilter24.eu/v1beta5
      kind: BitwardenSecret
      metadata:
        name: test
      spec:
        content:
          - element:
              secretName: username
              secretRef: nameofUser
          - element:
              secretName: password
              secretRef: passwordOfUser
        itemName: "SecretName"
        collectionPath: "Some/App/Identifier/Path"
        name: "test-secret-from-item-name"
        namespace: "default"
        labels:
          key: value
    - apiVersion: lerentis.uploadfilter24.eu/v1beta5
      kind: RegistryCredential
      metadata:
        name: test
      spec:
        usernameRef: "username"
        passwordRef: "password"
        registry: "docker.io"
        id: "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"
        name: "test-regcred"
        namespace: "default"
        labels:
          key: value
    - apiVersion: "lerentis.uploadfilter24.eu/v1beta5"
      kind: BitwardenTemplate
      metadata:
        name: test
      spec:
        filename: "config.yaml"
        name: "test-regcred"
        namespace: "default"
        labels:
          key: value
        template: |
          ---
          api:
            enabled: True
            key: {{ bitwarden_lookup("aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee", "fields", "key") }}
            allowCrossOrigin: false
            apps:
              "some.app.identifier:some_version":
                pubkey: {{ bitwarden_lookup("aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee", "attachment", "public_key") }}
                enabled: true
                username: {{ bitwarden_lookup_with_name("Some/App/Identifier/Path", "SecretName", "login", "username") }}
                specialField: {{ bitwarden_lookup_with_name("Some/App/Identifier/Path", "SecretName", "fields", "specialField") }}
                pvtkey: {{ bitwarden_lookup_with_name("Some/App/Identifier/Path", "SecretName", "attachment", "private_key") }}
  artifacthub.io/license: MIT
  artifacthub.io/operator: "true"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |
    - kind: changed
      description: "Update python to 3.11.8-r0"
    - kind: changed
      description: "Update Node to 20.11.1-r0"
    - kind: changed
      description: "Unified bw cli installation methode"
  artifacthub.io/images: |
    - name: bitwarden-crd-operator
      image: ghcr.io/lerentis/bitwarden-crd-operator:0.10.3
