apiVersion: v2
name: bitwarden-crd-operator
description: Deploy the Bitwarden CRD Operator

type: application

version: "v0.3.1"

appVersion: "0.2.1"

keywords:
  - operator
  - bitwarden
  - vaultwarden

home: https://lerentis.github.io/bitwarden-crd-operator/

sources:
  - https://github.com/Lerentis/bitwarden-crd-operator

kubeVersion: '>= 1.23.0-0'

maintainers:
  - name: lerentis
    email: lerentis+helm@uploadfilter24.eu

annotations:
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/Lerentis/bitwarden-crd-operator
  artifacthub.io/crds: |
    - kind: BitwardenSecret
      version: v1beta3
      name: bitwarden-secret
      displayName: Bitwarden Secret
      description: Management Object to create secrets from bitwarden
    - kind: RegistryCredential
      version: v1beta3
      name: registry-credential
      displayName: Regestry Credentials
      description: Management Object to create regestry secrets from bitwarden
  artifacthub.io/license: MIT
  artifacthub.io/operator: "true"  
  artifacthub.io/changes: |
    - kind: changed
      description: "Mainternence update and image rebuild to include upstream fixes"
  artifacthub.io/images: |
    - name: bitwarden-crd-operator
      image: lerentis/bitwarden-crd-operator:0.2.1
