apiVersion: v2
name: bitwarden-crd-operator
description: Deploy the Bitwarden CRD Operator

type: application

version: "v0.2.0"

appVersion: "0.1.2"

keywords:
  - operator
  - bitwarden
  - vaultwarden

home: https://lerentis.github.io/bitwarden-crd-operator/

sources:
  - https://github.com/Lerentis/bitwarden-crd-operator

kubeVersion: '>= 1.13.0-0'

maintainers:
  - name: lerentis
    email: lerentis+helm@uploadfilter24.eu

annotations:
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/Lerentis/bitwarden-crd-operator
  artifacthub.io/crds: |
    - kind: BitwardenSecret
      version: v1beta2
      name: bitwarden-secret
      displayName: Bitwarden Secret
      description: Management Object to create secrets from bitwarden
  artifacthub.io/license: MIT
  artifacthub.io/operator: "true"  
  artifacthub.io/changes: |
    - kind: changed
      description: "added possibility to configure operator from existing secret"
  artifacthub.io/images: |
    - name: bitwarden-crd-operator
      image: lerentis/bitwarden-crd-operator:0.1.2
