kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "bitwarden-crd-operator.serviceAccountName" . }}-role
rules:
- apiGroups: ["lerentis.uploadfilter24.eu"]
  resources: ["bitwarden-secrets"]
  verbs: ["get", "watch", "list", "create", "delete", "patch", "update"]
- apiGroups: ["v1"]
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "create", "delete", "patch", "update"]
- apiGroups: [""]
  resources: [events]
  verbs: [create]