name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Get app version from chart
        uses: mikefarah/yq@v4.30.6
        id: app_version
        with:
          cmd: yq '.appVersion' charts/bitwarden-crd-operator/Chart.yaml

      - name: Publish SBOM
        uses: anchore/sbom-action@v0
        with:
          image: lerentis/bitwarden-crd-operator:${{ steps.app_version.outputs.result }}
